version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - set arch=
  - if "%platform%"=="x64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
#  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - echo %generator%

before_build:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: cd C:\projects\LanDiscovery
  - cmd: git submodule update --init --recursive
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G %generator%

build:
  project: c:\projects\LanDiscovery\build\LanDiscovery.sln
  verbosity: minimal
  parallel: true